# Generated by Django 2.1.7 on 2019-11-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20191025_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='p_noteClass',
        ),
    ]
