# Generated by Django 2.1.7 on 2019-11-01 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0006_remove_userprofile_p_noteclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('time', models.DateField(auto_now_add=True, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('about', models.TextField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_sex',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p_username',
        ),
    ]
