# Generated by Django 2.1.7 on 2019-10-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('uptime', models.DateField(auto_now_add=True)),
                ('like', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('content', models.CharField(max_length=9999, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Note',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='noteClass',
            fields=[
                ('class_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='class_id')),
                ('class_name', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='usercomment',
            fields=[
                ('content', models.TextField(max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('note_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'like',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.SmallIntegerField(choices=[(0, 'administration'), (1, 'advisior')], default=1)),
                ('p_username', models.CharField(max_length=20, null=True)),
                ('p_name', models.CharField(max_length=50, null=True)),
                ('p_sex', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], null=True)),
                ('p_age', models.CharField(max_length=10, null=True)),
                ('p_time', models.DateField(auto_now_add=True, null=True)),
                ('p_phone', models.CharField(max_length=30, null=True)),
                ('p_email', models.EmailField(max_length=30, null=True)),
                ('p_photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('p_about', models.TextField(blank=True, max_length=100, null=True)),
                ('p_noteClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.noteClass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.noteClass'),
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
