# Generated by Django 2.1.7 on 2019-10-25 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20191020_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='tag_id')),
                ('tag_num', models.IntegerField(default=1)),
                ('tag_name', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Tag'),
        ),
    ]
