# Generated by Django 2.1.7 on 2019-11-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20191101_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='user_id',
        ),
    ]
